# language: node_js
# node_js:
#     - 7
#     - 8
#     - 9
#     - 10
#     - 11
#     - 12
#     - 13
#     - 14
#     - 15
#     - 16
#     - 17
#     - 18
#     - 19
#     - 20

# cache:
#     npm: true
#     directories:
#         - node_modules

# before_script:
#     - npm run build

# script:
#     - npm run lint
#     - npm run test
#     - npm run coverage

# after_success:
#     - npm install -g coveralls && npm run coverage:report | coveralls

# deploy:
#     provider: npm
#     email: $NPM_EMAIL_ADDRESS
#     api_key: $NPM_TOKEN
#     skip_cleanup: true
#     on:
#         tags: true
#         node: 20
