name: CI

on:
  pull_request:
    branches:
      - v*
    path:
      - 'src/**'
      - 'tests/**'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'

jobs:
  test:
    name: "Testing on node v${{ matrix.node-version }}"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 19, 20]

    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: npm run test
